print "RECOVERY MODE"
print "DEVELOPED BY W-H CO. 2015 (C)"
print "TO VIEW AVAILABLE COMMANDS ENTER THE COMMAND HELP. ALL COMMANDS NEED CAPITALS"
print "MY DIRECTORY IS F:/RECOVERY/SYS.SET"
print "DONE PREPARING. ENTER A COMMAND"
while True:
    print "F:/>"
    CMD = raw_input ("F:/>")
