print "PAGE 1: BASIC COMMANDS"
print ""
print "info: Shows information"
print "help: Shows commands"
print "stop: Stops system"
print "hello: says hello"
print "logout: logout"
print "catfish: special"
print "hello: Hello world!"
print "ping: pong!"
print "cls: clear display"
print "update: gets update from server (WILL SHUT DOWN)"
print "delete: Opens a launcher to delete a file"
print "etrash: Empties FOS Trash"
